/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebDevelopmentRouteImport } from './routes/web-development'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PosSystemsRouteImport } from './routes/pos-systems'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostingRouteImport } from './routes/hosting'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BulkSmsRouteImport } from './routes/bulk-sms'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard.tickets'
import { Route as DashboardSmsRouteImport } from './routes/dashboard.sms'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPosRouteImport } from './routes/dashboard.pos'
import { Route as DashboardHostingRouteImport } from './routes/dashboard.hosting'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminProvisioningRouteImport } from './routes/admin.provisioning'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as ApiSmsSendRouteImport } from './routes/api.sms.send'
import { Route as ApiProvisioningRunRouteImport } from './routes/api.provisioning.run'
import { Route as ApiMpesaStkPushRouteImport } from './routes/api.mpesa.stk-push'
import { Route as ApiMpesaStatusRouteImport } from './routes/api.mpesa.status'
import { Route as ApiMpesaCallbackRouteImport } from './routes/api.mpesa.callback'

const WebDevelopmentRoute = WebDevelopmentRouteImport.update({
  id: '/web-development',
  path: '/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PosSystemsRoute = PosSystemsRouteImport.update({
  id: '/pos-systems',
  path: '/pos-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingRoute = HostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkSmsRoute = BulkSmsRouteImport.update({
  id: '/bulk-sms',
  path: '/bulk-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmsRoute = DashboardSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPosRoute = DashboardPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHostingRoute = DashboardHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvisioningRoute = AdminProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSmsSendRoute = ApiSmsSendRouteImport.update({
  id: '/api/sms/send',
  path: '/api/sms/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvisioningRunRoute = ApiProvisioningRunRouteImport.update({
  id: '/api/provisioning/run',
  path: '/api/provisioning/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaStkPushRoute = ApiMpesaStkPushRouteImport.update({
  id: '/api/mpesa/stk-push',
  path: '/api/mpesa/stk-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaStatusRoute = ApiMpesaStatusRouteImport.update({
  id: '/api/mpesa/status',
  path: '/api/mpesa/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpesaCallbackRoute = ApiMpesaCallbackRouteImport.update({
  id: '/api/mpesa/callback',
  path: '/api/mpesa/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bulk-sms': typeof BulkSmsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/domains': typeof DomainsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/pos-systems': typeof PosSystemsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/web-development': typeof WebDevelopmentRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/sms': typeof DashboardSmsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa/status': typeof ApiMpesaStatusRoute
  '/api/mpesa/stk-push': typeof ApiMpesaStkPushRoute
  '/api/provisioning/run': typeof ApiProvisioningRunRoute
  '/api/sms/send': typeof ApiSmsSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk-sms': typeof BulkSmsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/domains': typeof DomainsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/pos-systems': typeof PosSystemsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/web-development': typeof WebDevelopmentRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/sms': typeof DashboardSmsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa/status': typeof ApiMpesaStatusRoute
  '/api/mpesa/stk-push': typeof ApiMpesaStkPushRoute
  '/api/provisioning/run': typeof ApiProvisioningRunRoute
  '/api/sms/send': typeof ApiSmsSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bulk-sms': typeof BulkSmsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/domains': typeof DomainsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hosting': typeof HostingRoute
  '/login': typeof LoginRoute
  '/pos-systems': typeof PosSystemsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/web-development': typeof WebDevelopmentRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/hosting': typeof DashboardHostingRoute
  '/dashboard/pos': typeof DashboardPosRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/sms': typeof DashboardSmsRoute
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/mpesa/callback': typeof ApiMpesaCallbackRoute
  '/api/mpesa/status': typeof ApiMpesaStatusRoute
  '/api/mpesa/stk-push': typeof ApiMpesaStkPushRoute
  '/api/provisioning/run': typeof ApiProvisioningRunRoute
  '/api/sms/send': typeof ApiSmsSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bulk-sms'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/domains'
    | '/forgot-password'
    | '/hosting'
    | '/login'
    | '/pos-systems'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/web-development'
    | '/admin/audit'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/provisioning'
    | '/admin/services'
    | '/admin/tickets'
    | '/admin/users'
    | '/dashboard/billing'
    | '/dashboard/domains'
    | '/dashboard/hosting'
    | '/dashboard/pos'
    | '/dashboard/profile'
    | '/dashboard/services'
    | '/dashboard/sms'
    | '/dashboard/tickets'
    | '/dashboard/wallet'
    | '/admin/'
    | '/dashboard/'
    | '/api/mpesa/callback'
    | '/api/mpesa/status'
    | '/api/mpesa/stk-push'
    | '/api/provisioning/run'
    | '/api/sms/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk-sms'
    | '/checkout'
    | '/contact'
    | '/domains'
    | '/forgot-password'
    | '/hosting'
    | '/login'
    | '/pos-systems'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/web-development'
    | '/admin/audit'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/provisioning'
    | '/admin/services'
    | '/admin/tickets'
    | '/admin/users'
    | '/dashboard/billing'
    | '/dashboard/domains'
    | '/dashboard/hosting'
    | '/dashboard/pos'
    | '/dashboard/profile'
    | '/dashboard/services'
    | '/dashboard/sms'
    | '/dashboard/tickets'
    | '/dashboard/wallet'
    | '/admin'
    | '/dashboard'
    | '/api/mpesa/callback'
    | '/api/mpesa/status'
    | '/api/mpesa/stk-push'
    | '/api/provisioning/run'
    | '/api/sms/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bulk-sms'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/domains'
    | '/forgot-password'
    | '/hosting'
    | '/login'
    | '/pos-systems'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/web-development'
    | '/admin/audit'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/provisioning'
    | '/admin/services'
    | '/admin/tickets'
    | '/admin/users'
    | '/dashboard/billing'
    | '/dashboard/domains'
    | '/dashboard/hosting'
    | '/dashboard/pos'
    | '/dashboard/profile'
    | '/dashboard/services'
    | '/dashboard/sms'
    | '/dashboard/tickets'
    | '/dashboard/wallet'
    | '/admin/'
    | '/dashboard/'
    | '/api/mpesa/callback'
    | '/api/mpesa/status'
    | '/api/mpesa/stk-push'
    | '/api/provisioning/run'
    | '/api/sms/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BulkSmsRoute: typeof BulkSmsRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DomainsRoute: typeof DomainsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HostingRoute: typeof HostingRoute
  LoginRoute: typeof LoginRoute
  PosSystemsRoute: typeof PosSystemsRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WebDevelopmentRoute: typeof WebDevelopmentRoute
  ApiMpesaCallbackRoute: typeof ApiMpesaCallbackRoute
  ApiMpesaStatusRoute: typeof ApiMpesaStatusRoute
  ApiMpesaStkPushRoute: typeof ApiMpesaStkPushRoute
  ApiProvisioningRunRoute: typeof ApiProvisioningRunRoute
  ApiSmsSendRoute: typeof ApiSmsSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-development': {
      id: '/web-development'
      path: '/web-development'
      fullPath: '/web-development'
      preLoaderRoute: typeof WebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-systems': {
      id: '/pos-systems'
      path: '/pos-systems'
      fullPath: '/pos-systems'
      preLoaderRoute: typeof PosSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting': {
      id: '/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof HostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-sms': {
      id: '/bulk-sms'
      path: '/bulk-sms'
      fullPath: '/bulk-sms'
      preLoaderRoute: typeof BulkSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sms': {
      id: '/dashboard/sms'
      path: '/sms'
      fullPath: '/dashboard/sms'
      preLoaderRoute: typeof DashboardSmsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pos': {
      id: '/dashboard/pos'
      path: '/pos'
      fullPath: '/dashboard/pos'
      preLoaderRoute: typeof DashboardPosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hosting': {
      id: '/dashboard/hosting'
      path: '/hosting'
      fullPath: '/dashboard/hosting'
      preLoaderRoute: typeof DashboardHostingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/provisioning': {
      id: '/admin/provisioning'
      path: '/provisioning'
      fullPath: '/admin/provisioning'
      preLoaderRoute: typeof AdminProvisioningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/sms/send': {
      id: '/api/sms/send'
      path: '/api/sms/send'
      fullPath: '/api/sms/send'
      preLoaderRoute: typeof ApiSmsSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/provisioning/run': {
      id: '/api/provisioning/run'
      path: '/api/provisioning/run'
      fullPath: '/api/provisioning/run'
      preLoaderRoute: typeof ApiProvisioningRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/stk-push': {
      id: '/api/mpesa/stk-push'
      path: '/api/mpesa/stk-push'
      fullPath: '/api/mpesa/stk-push'
      preLoaderRoute: typeof ApiMpesaStkPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/status': {
      id: '/api/mpesa/status'
      path: '/api/mpesa/status'
      fullPath: '/api/mpesa/status'
      preLoaderRoute: typeof ApiMpesaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mpesa/callback': {
      id: '/api/mpesa/callback'
      path: '/api/mpesa/callback'
      fullPath: '/api/mpesa/callback'
      preLoaderRoute: typeof ApiMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminProvisioningRoute: typeof AdminProvisioningRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminProvisioningRoute: AdminProvisioningRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardHostingRoute: typeof DashboardHostingRoute
  DashboardPosRoute: typeof DashboardPosRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSmsRoute: typeof DashboardSmsRoute
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardHostingRoute: DashboardHostingRoute,
  DashboardPosRoute: DashboardPosRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSmsRoute: DashboardSmsRoute,
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BulkSmsRoute: BulkSmsRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DomainsRoute: DomainsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HostingRoute: HostingRoute,
  LoginRoute: LoginRoute,
  PosSystemsRoute: PosSystemsRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WebDevelopmentRoute: WebDevelopmentRoute,
  ApiMpesaCallbackRoute: ApiMpesaCallbackRoute,
  ApiMpesaStatusRoute: ApiMpesaStatusRoute,
  ApiMpesaStkPushRoute: ApiMpesaStkPushRoute,
  ApiProvisioningRunRoute: ApiProvisioningRunRoute,
  ApiSmsSendRoute: ApiSmsSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
