
-- ============ PLANS CATALOG ============
CREATE TABLE public.plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  type service_type NOT NULL,
  name text NOT NULL,
  tagline text,
  description text,
  price numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'KES',
  billing_cycle billing_cycle NOT NULL DEFAULT 'monthly',
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "plans: public read active"
  ON public.plans FOR SELECT
  USING (is_active = true OR is_staff(auth.uid()));

CREATE POLICY "plans: staff manage"
  ON public.plans FOR ALL
  USING (is_staff(auth.uid()))
  WITH CHECK (is_staff(auth.uid()));

CREATE TRIGGER plans_updated_at
  BEFORE UPDATE ON public.plans
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============ CART ============
CREATE TABLE public.cart_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_id uuid REFERENCES public.plans(id) ON DELETE CASCADE,
  -- For domain searches without a plan row:
  custom_name text,
  custom_type service_type,
  custom_price numeric,
  custom_billing_cycle billing_cycle,
  domain_name text,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity >= 1),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "cart: own all"
  ON public.cart_items FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX idx_cart_user ON public.cart_items(user_id);

-- ============ PAYMENT ATTEMPTS ============
CREATE TYPE public.payment_attempt_status AS ENUM (
  'initiated', 'pending', 'success', 'failed', 'cancelled', 'timeout'
);

CREATE TABLE public.payment_attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  invoice_id uuid REFERENCES public.invoices(id) ON DELETE SET NULL,
  purpose text NOT NULL DEFAULT 'invoice', -- 'invoice' | 'wallet_topup'
  method payment_method NOT NULL,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'KES',
  phone text,
  status payment_attempt_status NOT NULL DEFAULT 'initiated',
  provider_request_id text,
  provider_receipt text,
  provider_response jsonb,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.payment_attempts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "payments: own select"
  ON public.payment_attempts FOR SELECT
  USING (auth.uid() = user_id OR is_staff(auth.uid()));

CREATE POLICY "payments: own insert"
  ON public.payment_attempts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "payments: staff update"
  ON public.payment_attempts FOR UPDATE
  USING (is_staff(auth.uid()));

CREATE TRIGGER payments_updated_at
  BEFORE UPDATE ON public.payment_attempts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX idx_payments_user ON public.payment_attempts(user_id);
CREATE INDEX idx_payments_invoice ON public.payment_attempts(invoice_id);
CREATE INDEX idx_payments_provider_req ON public.payment_attempts(provider_request_id);

-- ============ ATOMIC RPC: create_invoice_from_cart ============
CREATE OR REPLACE FUNCTION public.create_invoice_from_cart()
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_invoice_id uuid;
  v_subtotal numeric := 0;
  v_item record;
  v_unit_price numeric;
  v_item_name text;
  v_item_type service_type;
  v_item_cycle billing_cycle;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM cart_items WHERE user_id = v_user) THEN
    RAISE EXCEPTION 'Cart is empty';
  END IF;

  -- Compute subtotal
  SELECT COALESCE(SUM(
    COALESCE(p.price, ci.custom_price, 0) * ci.quantity
  ), 0) INTO v_subtotal
  FROM cart_items ci
  LEFT JOIN plans p ON p.id = ci.plan_id
  WHERE ci.user_id = v_user;

  -- Create invoice (number auto-generated by trigger)
  INSERT INTO invoices (user_id, status, subtotal, tax, total, currency, due_at)
  VALUES (v_user, 'unpaid', v_subtotal, 0, v_subtotal, 'KES', now() + interval '7 days')
  RETURNING id INTO v_invoice_id;

  -- Create invoice items + pending services
  FOR v_item IN
    SELECT ci.*, p.name AS plan_name, p.type AS plan_type,
           p.billing_cycle AS plan_cycle, p.price AS plan_price
    FROM cart_items ci
    LEFT JOIN plans p ON p.id = ci.plan_id
    WHERE ci.user_id = v_user
  LOOP
    v_unit_price := COALESCE(v_item.plan_price, v_item.custom_price, 0);
    v_item_name := COALESCE(v_item.plan_name, v_item.custom_name, 'Service');
    v_item_type := COALESCE(v_item.plan_type, v_item.custom_type);
    v_item_cycle := COALESCE(v_item.plan_cycle, v_item.custom_billing_cycle, 'monthly');

    INSERT INTO invoice_items (invoice_id, description, quantity, unit_price, amount)
    VALUES (
      v_invoice_id,
      v_item_name || COALESCE(' (' || v_item.domain_name || ')', ''),
      v_item.quantity,
      v_unit_price,
      v_unit_price * v_item.quantity
    );

    IF v_item_type IS NOT NULL THEN
      INSERT INTO services (user_id, type, name, domain_name, billing_cycle, price, currency, status, metadata)
      VALUES (
        v_user, v_item_type, v_item_name, v_item.domain_name,
        v_item_cycle, v_unit_price, 'KES', 'pending',
        jsonb_build_object('invoice_id', v_invoice_id, 'plan_id', v_item.plan_id)
      );
    END IF;
  END LOOP;

  -- Clear cart
  DELETE FROM cart_items WHERE user_id = v_user;

  RETURN v_invoice_id;
END;
$$;

-- ============ ATOMIC RPC: pay_invoice_with_wallet ============
CREATE OR REPLACE FUNCTION public.pay_invoice_with_wallet(_invoice_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_invoice invoices;
  v_balance numeric;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT * INTO v_invoice FROM invoices
  WHERE id = _invoice_id AND user_id = v_user
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invoice not found';
  END IF;

  IF v_invoice.status = 'paid' THEN
    RETURN jsonb_build_object('ok', true, 'message', 'Already paid');
  END IF;

  SELECT balance INTO v_balance FROM wallet_balances
  WHERE user_id = v_user FOR UPDATE;

  IF COALESCE(v_balance, 0) < v_invoice.total THEN
    RAISE EXCEPTION 'Insufficient wallet balance';
  END IF;

  -- Debit wallet
  UPDATE wallet_balances
  SET balance = balance - v_invoice.total, updated_at = now()
  WHERE user_id = v_user;

  -- Ledger
  INSERT INTO wallet_transactions (user_id, type, amount, currency, description, invoice_id)
  VALUES (v_user, 'payment', v_invoice.total, v_invoice.currency,
          'Payment for invoice ' || v_invoice.invoice_number, v_invoice.id);

  -- Mark invoice paid
  UPDATE invoices
  SET status = 'paid', paid_at = now(), payment_method = 'wallet', updated_at = now()
  WHERE id = _invoice_id;

  -- Activate services tied to this invoice
  UPDATE services
  SET status = 'active',
      next_renewal_at = CASE billing_cycle
        WHEN 'monthly'      THEN now() + interval '1 month'
        WHEN 'quarterly'    THEN now() + interval '3 months'
        WHEN 'semi_annually' THEN now() + interval '6 months'
        WHEN 'annually'     THEN now() + interval '1 year'
        ELSE NULL
      END,
      updated_at = now()
  WHERE user_id = v_user
    AND (metadata->>'invoice_id')::uuid = _invoice_id
    AND status = 'pending';

  RETURN jsonb_build_object('ok', true, 'invoice_id', _invoice_id);
END;
$$;

-- ============ ATOMIC RPC: credit_wallet_topup (used after M-Pesa success) ============
CREATE OR REPLACE FUNCTION public.credit_wallet_topup(_user_id uuid, _amount numeric, _description text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Only callable via service role (admin client) or staff
  IF NOT (is_staff(auth.uid()) OR auth.uid() IS NULL) THEN
    RAISE EXCEPTION 'Forbidden';
  END IF;

  UPDATE wallet_balances
  SET balance = balance + _amount, updated_at = now()
  WHERE user_id = _user_id;

  INSERT INTO wallet_transactions (user_id, type, amount, currency, description)
  VALUES (_user_id, 'deposit', _amount, 'KES', _description);
END;
$$;

-- ============ SEED CATALOG ============
INSERT INTO public.plans (slug, type, name, tagline, description, price, billing_cycle, features, sort_order) VALUES
-- Hosting
('hosting-starter', 'hosting', 'Starter Hosting', 'Perfect for small sites', 'Single website hosting with SSL and email.',
 299, 'monthly',
 '["1 website","10 GB SSD storage","Free SSL certificate","5 email accounts","Daily backups","99.9% uptime SLA"]'::jsonb, 10),
('hosting-business', 'hosting', 'Business Hosting', 'Best for growing businesses', 'Unlimited websites with priority support.',
 799, 'monthly',
 '["Unlimited websites","50 GB SSD storage","Free SSL certificates","Unlimited email accounts","Daily backups","Priority support","Free domain (.co.ke) for 1 year"]'::jsonb, 20),
('hosting-pro', 'hosting', 'Pro Hosting', 'For high-traffic sites', 'Premium performance with WAF and CDN.',
 1999, 'monthly',
 '["Unlimited websites","200 GB NVMe SSD","Free SSL + CDN","Unlimited emails","Hourly backups","Web Application Firewall","24/7 priority support","Free .com domain"]'::jsonb, 30),

-- POS Systems
('pos-retail', 'pos', 'POS Retail', 'For shops and supermarkets', 'Full retail POS with inventory and barcode scanning.',
 1500, 'monthly',
 '["Unlimited products","Barcode scanning","Multi-branch","Inventory management","Sales analytics","M-Pesa integration","Cashier accounts"]'::jsonb, 40),
('pos-restaurant', 'pos', 'POS Restaurant', 'For restaurants and cafés', 'Table management, kitchen display and recipes.',
 1800, 'monthly',
 '["Table & order management","Kitchen display system","Menu & recipes","Split bills","Waiter app","Daily Z-reports","M-Pesa integration"]'::jsonb, 50),
('pos-pharmacy', 'pos', 'POS Pharmacy', 'For pharmacies & chemists', 'Drug catalog with expiry tracking and prescriptions.',
 2000, 'monthly',
 '["Drug catalog","Expiry & batch tracking","Prescription records","Supplier management","Insurance support","M-Pesa integration"]'::jsonb, 60),
('pos-liquor', 'pos', 'POS Liquor', 'For bars & wines and spirits', 'Stock per bottle with shift reporting.',
 1700, 'monthly',
 '["Bottle-level stock","Shift reports","Tabs & happy hour","Multi-cashier","M-Pesa integration"]'::jsonb, 70),

-- SMS
('sms-starter', 'sms', 'SMS Starter', '1,000 SMS bundle', 'Bulk SMS for small campaigns.',
 800, 'one_time',
 '["1,000 SMS units","Sender ID setup","Delivery reports","Web dashboard","API access"]'::jsonb, 80),
('sms-business', 'sms', 'SMS Business', '10,000 SMS bundle', 'For growing campaigns and notifications.',
 7500, 'one_time',
 '["10,000 SMS units","Sender ID setup","Delivery reports","Contact groups","Scheduled sends","API access"]'::jsonb, 90),
('sms-enterprise', 'sms', 'SMS Enterprise', '100,000 SMS bundle', 'Best per-unit price for high volume.',
 65000, 'one_time',
 '["100,000 SMS units","Multiple sender IDs","Priority routing","Detailed analytics","API + webhook","Dedicated account manager"]'::jsonb, 100),

-- Web Development (project-based)
('web-landing', 'web_development', 'Landing Page', 'Single-page website', 'Modern responsive landing page with contact form.',
 25000, 'one_time',
 '["1-page design","Mobile responsive","Contact form","Basic SEO","2 revisions","Delivery in 7 days"]'::jsonb, 110),
('web-business', 'web_development', 'Business Website', '5–8 page website', 'Full corporate website with CMS.',
 65000, 'one_time',
 '["Up to 8 pages","Mobile responsive","CMS (edit content yourself)","Contact & quote forms","On-page SEO","5 revisions","Delivery in 21 days"]'::jsonb, 120),
('web-ecommerce', 'web_development', 'E-commerce Store', 'Online shop', 'Full e-commerce with M-Pesa & card checkout.',
 150000, 'one_time',
 '["Unlimited products","M-Pesa & card checkout","Inventory","Order management","Customer accounts","Delivery in 45 days"]'::jsonb, 130);
